[package]
name = "py-forust"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "forust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28", features = ["extension-module"] }
forust-ml = { version = "0.5.0", path = "../" }
numpy = "0.28"
ndarray = "0.17"
serde_plain = { version = "1.0" }
serde = { version = "1.0" }
pyo3-log = "0.13.3"
