[project]
name = "forust"
dynamic = ["version"]
description = "A lightweight gradient boosting implementation in Rust."
license = { file = "LICENSE" }
keywords = [
  "rust",
  "forust",
  "machine learning",
  "xgboost",
  "tree model",
  "decision tree",
]
authors = [{ name = "James Inlow" }]
readme = "README.md"
dependencies = ["numpy>=1.21", "pandas>=1.3"]
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]

[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = ["maturin", "pytest", "seaborn", "xgboost<2.0", "scikit-learn", "ruff>=0.0.272"]
docs = ["mkdocs-material==9.*", "mkdocstrings==0.29.1", "mkdocstrings-python==1.16.10", "mkdocs-autorefs==1.4.1", "mkdocs<2.0.0"]

[tool.maturin]
sdist-include = ["LICENSE", "README.md"]

[tool.uv]
# Rebuild package when any rust files change
cache-keys = [{file = "pyproject.toml"}, {file = "rust/Cargo.toml"}, {file = "**/*.rs"}]
# Uncomment to build rust code in development mode
# config-settings = { build-args = '--profile=dev' }

[tool.ruff]
# Never enforce `E501` (line length violations).
ignore = ["E501"]

[tool.isort]
profile = "black"
