name: docs
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          cp README.md py-forust/README.md
          cp LICENSE py-forust/LICENSE
      - run: pip install mkdocs-material
      - run: |
          cd py-forust
          uv sync --group dev --group docs
          uv run --group dev --group docs mkdocs gh-deploy --force
